AWSTemplateFormatVersion: 2010-09-09
Resources:
  AlertTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: AWS Alerts
      TopicName: alerts
      Subscription:
        - Endpoint: { "Ref" : "EmailParameter" }
          Protocol: 'email'
        - Endpoint: { "Ref" : "SMSParameter" }
          Protocol: 'SMS'
  BillingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alert if Estimated Charges surpass threshold"
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
        - Name: Currency
          Value: USD
      Statistic: Maximum
      Period: 21600
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: [ !Ref AlertTopic ]
Parameters:
  EmailParameter:
    Type: String
    Default: no-reply@aws.com
    Description: The email address to subscribe to alerts
  SMSParameter:
    Type: String
    Default: +1
    Description: The phone number to get sms alerts

Outputs:
  SNSTopic:
    Description: SNS Topic for Alerts
    Value: !Ref AlertTopic
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SNSTopic"